name: matomo-docker

services:
  anubis:
    image: ghcr.io/techarohq/anubis:v${ANUBIS_VERSION}
    container_name: anubis
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - ./botPolicies.yml:/doc/botPolicies.yaml:ro
    environment:
      - BIND=:8081
      - TARGET=http://web:80
      - REDIRECT_DOMAINS=${ANUBIS_REDIRECT_DOMAINS}
      - ED25519_PRIVATE_KEY_HEX=${ANUBIS_ED25519_PRIVATE_KEY_HEX}
      - POLICY_FNAME=/doc/botPolicies.yaml
    ports:
      - "127.0.0.1:8081:8080"
    networks:
      - backend
      - nginx-proxy-manager_frontend
      - app
    restart: unless-stopped
    labels:
      - wud.tag.include=^v\d+\.\d+\.\d+$$
      - traefik.enable=true
      - traefik.http.routers.anubis-matomo-docker.rule=Host(`matomo.dhjensen.dk`)
      - traefik.http.middlewares.ipallowall.ipAllowList.sourceRange=0.0.0.0/0
      - traefik.http.routers.anubis-matomo-docker.middlewares=ipallowall@docker

  app:
    image: matomo:${MATOMO_VERSION}-fpm-alpine
    container_name: app
    volumes:
      - matomo:/var/www/html:z
      - /etc/timezone:/etc/timezone:ro
    environment:
      - MATOMO_DATABASE_HOST
      - MATOMO_DATABASE_ADAPTER
      - MATOMO_DATABASE_TABLES_PREFIX
      - MATOMO_DATABASE_USERNAME
      - MATOMO_DATABASE_PASSWORD
      - MATOMO_DATABASE_DBNAME
    networks:
      - app
      - db
    restart: unless-stopped
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+-fpm-alpine$$
      - wud.watch.digest=true
      - traefik.enable=false

  db:
    image: mariadb:${MARIADB_VERSION}
    container_name: db
    volumes:
      - db:/var/lib/mysql:Z
      - /etc/timezone:/etc/timezone:ro
    environment:
      - MARIADB_AUTO_UPGRADE
      - MARIADB_DISABLE_UPGRADE_BACKUP
      - MARIADB_INITDB_SKIP_TZINFO
      - MARIADB_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
    networks:
      - db
    command: --max-allowed-packet=64MB
    restart: unless-stopped
    labels:
      - wud.watch.digest=true
      - traefik.enable=false

  web:
    image: nginx:${NGINX_VERSION}-alpine
    container_name: web
    volumes:
      - matomo:/var/www/html:z,ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:z,ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - frontend
      - app
    restart: unless-stopped
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+-alpine$$
      - traefik.enable=false

networks:
  backend:
    external: true
    driver: bridge
  nginx-proxy-manager_frontend:
    driver: bridge
    external: true
  frontend:
    driver: bridge
  app:
    driver: bridge
  db:
    driver: bridge

volumes:
  db:
  matomo:
