services:
  db:
    image: mariadb:lts
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql:Z
    environment:
      - MARIADB_AUTO_UPGRADE
      - MARIADB_DISABLE_UPGRADE_BACKUP
      - MARIADB_INITDB_SKIP_TZINFO
      - MARIADB_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER

  app:
    image: matomo:${MATOMO_VERSION}-fpm-alpine
    restart: always
    links:
      - db
    volumes:
      # - ./config:/var/www/html/config:z
      # - ./logs:/var/www/html/logs:z
      - matomo:/var/www/html:z
    environment:
      - MATOMO_DATABASE_HOST
      - MATOMO_DATABASE_ADAPTER
      - MATOMO_DATABASE_TABLES_PREFIX
      - MATOMO_DATABASE_USERNAME
      - MATOMO_DATABASE_PASSWORD
      - MATOMO_DATABASE_DBNAME

  web:
    image: nginx:alpine
    restart: always
    volumes:
      - matomo:/var/www/html:z,ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:z,ro
      - certacme:/var/www/certbot/:ro
      - cert:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443

  cert:
    image: certbot/certbot:latest
    volumes:
      - certacme:/var/www/certbot/:rw
      - cert:/etc/letsencrypt/:rw

  wt:
    image: containrrr/watchtower:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db:
  matomo:
  cert:
  certacme:
