name: matomo-docker

services:
  anubis:
    image: ghcr.io/techarohq/anubis:v${ANUBIS_VERSION}
    environment:
      - BIND=:8081
      - TARGET=http://web:80
    ports:
      - "127.0.0.1:8081:8080"
    networks:
      - nginx-proxy-manager_frontend
      - app
    restart: always

  app:
    image: matomo:${MATOMO_VERSION}-fpm-alpine
    volumes:
      - matomo:/var/www/html:z
    environment:
      - MATOMO_DATABASE_HOST
      - MATOMO_DATABASE_ADAPTER
      - MATOMO_DATABASE_TABLES_PREFIX
      - MATOMO_DATABASE_USERNAME
      - MATOMO_DATABASE_PASSWORD
      - MATOMO_DATABASE_DBNAME
    networks:
      - app
      - db
    restart: always
    links:
      - db

  db:
    image: mariadb:${MARIADB_VERSION}
    volumes:
      - db:/var/lib/mysql:Z
    environment:
      - MARIADB_AUTO_UPGRADE
      - MARIADB_DISABLE_UPGRADE_BACKUP
      - MARIADB_INITDB_SKIP_TZINFO
      - MARIADB_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
    networks:
      - db
    command: --max-allowed-packet=64MB
    restart: always

  web:
    image: nginx:${NGINX_VERSION}-alpine
    volumes:
      - matomo:/var/www/html:z,ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:z,ro
    networks:
      - frontend
      - app
    restart: always

  wt:
    image: containrrr/watchtower:${WATCHTOWER_VERSION}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

networks:
  nginx-proxy-manager_frontend:
    driver: bridge
    external: true
  frontend:
    driver: bridge
  app:
    driver: bridge
  db:
    driver: bridge

volumes:
  db:
  matomo:
